### ISSUE TITLE
TODO - 수강

### ISSUE THREAD

**Issue by sgju-placea** [YeonjuOHYE/WebGL#11]
- [x] 다중 애니메이션 요소 최적화하기 
- [x] 물체를 마우스로 피킹하기 
- [x] 물체의 투명도 설정하기
- [x] three.js 배경과 하늘상자
- [x] circle, triangle template 구문 검토
- [x] fog project 완성 
- [x] TextureGui 프로젝트 완성
- [x] 썸네일 등록 자동화 고민
